"use client";

import type { Metadata } from "next";
import "@/styles/global.scss";
import { manrope } from "@/fonts/fonts";
import NextTopLoader from "nextjs-toploader";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={manrope.variable}>
      <body>
        <NextTopLoader color="#C59B68" />
        {children}
      </body>
    </html>
  );
}
